# [Combine] Operator: Mapping

###### tags: `Combine`

### 목차

- **Mapping**
- Filtering
- Reducing
- Mathematical Operations
- Applying Matching Criteria
- Applying Sequence Operations
- Selecting Specific Elements
- CombineLatest
- Merge
- Zip
- FlatMap
- Handling Errors
- Controlling Timing
- Encoding and Decoding
- Identifying Properties with Key Paths
- Working with Multiple Subscribers
- Buffering Elements
- Performing Type-Erasure
- Specifying Schedulers
- Adding Explicit Connectability
- Connecting Simple Subscribers
- Debugging

Operator가 너무 많아서 걱정했는데, 공식문서에 다 있더라구요? 근데 개많음.. ㅠㅠ
이 밑에 있는 친구들을 하나씩 봐보려고 합니다!

오늘은 첫번째 Mapping Operator에 대해서 공부해보겠습니다 :)


### map(_:)

> Transforms all elements from the upstream publisher with a provided closure.

upstream publisher의 모든 elements를 클로져대로 transfroms한다고 함

그냥 swift에서 저희가 아는 map이랑 완전 똑같습니다.

```swift
let campers = ["dudu", "safari", "malrang", "mino"]

campers.publisher
    .map { $0 + " 입니다"}
    .sink { str in
        print(str)
    }

/*
dudu 입니다
safari 입니다
malrang 입니다
mino 입니다
*/
```

### tryMap(_:)

> Transforms all elements from the upstream publisher with a provided error-throwing closure.

위랑 가장 다른건.. try라는 네이밍에서도 알 수 있듯이 요 operator는 map의 연산결과가 에러를 발생시킬때 사용합니다. 즉 closure가 throw를 던질때 사용해야하는 친구에요!

```swift
enum MyError: Error {
    case all
}

let campers = ["dudu", "safari", "malrang", "mino"]

func goodCampers(name: String) throws -> String {
    if name == "dudu" {
        throw MyError.all
    } else {
        return name + "은 착해요"
    }
}

campers.publisher
    .tryMap(goodCampers(name:))
    .sink { result in
        print(result)
    } receiveValue: { str in
        print(str)
    }

// failure(__lldb_expr_495.MyError.all)
```

참고로 말을 안한거 같은데, 에러 발생시 그즉시 종료되고, 그 다음 이벤트들은 전달되지 않습니다

### mapError(_:)

> Converts any failure from the upstream publisher into a new error.

그니깐.. upstream에서 발생한 실패를 새로운 에러로 바꿔주는거 같은데요?
이게 왜 필요하지?

```swift
enum MyError: Error {
    case all
}

enum NewError: Error {
    case all
}

let campers = ["dudu", "safari", "malrang", "mino"]

func goodCampers(name: String) throws -> String {
    if name == "dudu" {
        throw MyError.all
    } else {
        return name + "은 착해요"
    }
}

campers.publisher
    .tryMap(goodCampers(name:))
    .mapError{ _ in NewError.all }
    .sink { result in
        print(result)
    } receiveValue: { str in
        print(str)
    }

// failure(__lldb_expr_505.NewError.all)
```

에러 타입이 달라진걸 확인할 수 있습니다

### replaceNil(with:)

> Replaces nil elements in the stream with the provided element.

nil 값을, 지정한 값으로 바꿔줍니다. 오케오케..

```swift
let campers = ["dudu", "safari", "malrang", "mino", nil]

campers.publisher
    .replaceNil(with: "누구세요?")
    .sink { print($0) }
/*
Optional("dudu")
Optional("safari")
Optional("malrang")
Optional("mino")
Optional("누구세요?")
*/
```

### scan(_:_)

> Transforms elements from the upstream publisher by providing the current element to a closure along with the last value returned by the closure.

초기값이 있고, element들을 거기에 하나씩 더하면서, 누적된 값들을 계속 방출합니다..!
한번 예제보면 바로 이해가 될거에요

```swift
let campers = ["dudu", "safari", "malrang", "mino"]

campers.publisher
    .scan("camper: ", +)
    .sink{ print($0) }

/*
camper: dudu
camper: dudusafari
camper: dudusafarimalrang
camper: dudusafarimalrangmino
*/
```

처음에는 초기값 + 첫번째 원소
두번째는 이전결과 + 두번째 원소...
이런식으로 되는거죠?

### tryScan(_:_)

> Transforms elements from the upstream publisher by providing the current element to an error-throwing closure along with the last value returned by the closure.

scan이랑 똑같은데, 클로져가 오류 던지는 친구일때 쓰는거죠?

```swift
func add(_ name1: String, _ name2: String) throws -> String {
    if name1.count >= 10 {
        throw MyError.all
    } else {
        return name1 + name2
    }
}

let campers = ["dudu", "safari", "malrang", "mino"]

campers.publisher
    .tryScan("") { try add($0,$1) }
    .sink(
        receiveCompletion: { print($0)},
        receiveValue: { print($0) }
    )

/*
dudu
dudusafari
failure(__lldb_expr_613.MyError.all)
*/
```

총 길이가 10 넘었을때 오류를 발생시키는 모습을 볼 수 있습니다 :)

### setFailureType(to:)

> Changes the failure type declared by the upstream publisher.

절대 에러가 안나는 publisher를 Error가 발생하는 publisher처럼 취급하고 싶을때 사용합니다.
이게 대체 뭔소린가 싶죠..?

예를들어 아래처럼 쓰는거죠?
campers.publisher는 죽어도 에러 안나는데.. 강제로 MyError을 발생시키는 친구로 만들어 버릴수 있습니다.

```swift
let campers = ["dudu", "safari", "malrang", "mino"]

campers.publisher
    .setFailureType(to: MyError.self)
```

사용법은 알겠는데, 어차피 에러 안나는데 이게 먼짓거리나구요?

combine에서는 publisher끼리 결합할 일이 많겠죠?
여러 비동기 이벤트 스트림을 묶어서 처리할 일이 많을테니깐..?
이때 Error 타입이 다르다면 묶지 못합니다!! 그 경우를 대비한 연산자 같네요

예를들어 zip연산자의 경우 아래와 같이 사용해야 합니다!

```swift
let campers = ["dudu", "safari", "malrang", "mino"]
let p2 = CurrentValueSubject<String, MyError>("first")

campers.publisher
    .setFailureType(to: MyError.self)
    .zip(p2)
    .sink(
        receiveCompletion: { print($0) },
        receiveValue: {print($0)}
    )
```

이렇게 Mapping Operator에 대해서 마쳤는데, 전혀 어렵지 않죠?
그 다음은 Filtering Operator인데, 얘는 더 쉬울것 같네요!
힘내서 얼릉 정리해 보도록 하겠습니다 :)
